CREATE OR REPLACE FUNCTION CAL_ANNSAL
(VEMPNO IN EMP.EMPNO%TYPE)
RETURN NUMBER
IS
  VANNSAL NUMBER(7,2);
BEGIN
  SELECT SAL * 12 + NVL(COMM,0)
  INTO VANNSAL
  FROM EMP
  WHERE EMPNO = VEMPNO;

  RETURN VANNSAL;
END;
/