SET SERVEROUTPUT ON
CREATE OR REPLACE PROCEDURE SEL_EMP
IS
    VEMP EMP%ROWTYPE;
    CURSOR C1
    IS
    SELECT EMPNO, ENAME, JOB, SAL FROM EMP;
BEGIN
    DBMS_OUTPUT.PUT_LINE('사번 / 사원명 / 직급 / 급여');
    DBMS_OUTPUT.PUT_LINE('----------------------------');

    OPEN C1;
LOOP
    FETCH C1 INTO VEMP;
    EXIT WHEN C1%NOTFOUND;

    DBMS_OUTPUT.PUT_LINE(VEMP.EMPNO || '    ' || VEMP.ENAME || '    ' || VEMP.JOB || '    ' || VEMP.SAL);
END LOOP;

CLOSE C1;
END;
/