CREATE OR REPLACE FUNCTION SEL_EMPNAME02
(VENAME IN EMP.ENAME%TYPE)
RETURN VARCHAR2
IS
VAR_JOB VARCHAR2(20);
BEGIN
  SELECT JOB
  INTO VAR_JOB
  FROM EMP
  WHERE ENAME = VENAME;

  RETURN VAR_JOB;
END;
/