CREATE OR REPLACE PROCEDURE SEL_EMPNAME2
(VENAME         IN EMP.ENAME%TYPE,
 VAR_JOB         OUT EMP.JOB%TYPE,
 VAR_DNAME    OUT DEPT.DNAME%TYPE
)
IS
BEGIN
    SELECT JOB, DNAME
    INTO   VAR_JOB, VAR_DNAME
    FROM  EMP NATURAL JOIN DEPT
    WHERE ENAME = VENAME;
END;
/