SET SERVEROUTPUT ON
DECLARE
  VEMPNO EMP.EMPNO%TYPE;
  VDNAME VARCHAR2(14);
  VENAME EMP.ENAME%TYPE;
BEGIN
  DBMS_OUTPUT.PUT_LINE('사번/이름/부서명');
  DBMS_OUTPUT.PUT_LINE('------------------------------');
  
  SELECT 
  EMPNO, ENAME, DNAME 
  INTO VEMPNO, VENAME, VDNAME
  FROM
  EMP NATURAL JOIN DEPT WHERE ENAME = 'SCOTT';

  DBMS_OUTPUT.PUT_LINE(VEMPNO||'/'||VENAME||'/'||VDNAME);
END;
/