SET SERVEROUTPUT ON

DECLARE
    VEMPNO EMP.EMPNO%TYPE;
    VENAME  EMP.ENAME%TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('사번/이름');
    DBMS_OUTPUT.PUT_LINE('----------------');

    SELECT EMPNO, ENAME
    INTO VEMPNO, VENAME
    FROM EMP
    WHERE ENAME = 'SCOTT';

    DBMS_OUTPUT.PUT_LINE(VEMPNO || '/' || VENAME);
END;
/